services:
  mariadb:
    container_name: mariadb
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - mariadb-db:/var/lib/mysql

    # network:
    #   - inception
  
  # wordpress:
  #   container_name: wordpress
  #   build:
  #     context: requirements/wordpress
  #     dockerfile: Dockerfile
    # volumes:
    # network:
    #   - inception
    # depends_on:
    #   - mariadb

  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
    # network:
    #   - inception
    # depends_on:
    #   - wordpress

# network:
#   inception:
#     driver: bridge

volumes:
  mariadb-db:
